#!/bin/bash

# CHROMIUM_ROOT can be specified in environment,
#
# On MacOS, this will generate <project>.xcodeproj which can be built.
# On Linux, this will add our target to ${CHROMIUM_ROOT}/Makefile
# so build using that.

# Currently building with Chromium r63660

while getopts ":c:" opt; do
  case $opt in
    c)
      CHROMIUM_ROOT=$OPTARG
      ;;
    \?)
      echo "Usage: $0 [-c <chromium-root>] <project.gyp>" >&2
      exit 1
      ;;
    :)
      echo "-$OPTARG missing argument." >&2
      exit 1
      ;;
  esac
done
shift $(expr $OPTIND - 1)

CURDIR=$(cd $(dirname "$0") && pwd)
"${CHROMIUM_ROOT:?}/build/gyp_chromium" --include="$CURDIR/variables.gypi" --toplevel-dir="${CHROMIUM_ROOT}" --depth="${CHROMIUM_ROOT}" "$1"
