#!/usr/bin/env bash

BASEDIR=$(dirname "${BASH_SOURCE[0]}")

# Clean up assets that may have been generated on another platform
rm -f $BASEDIR/../../../build/*.mov $MOUNT/../*.raw $MOUNT/../../../build/*.qsb
