#!/usr/bin/env bash

if [[ ${#} -eq 0 ]]; then
    echo "Usage: $(basename $0) [-d DURATION] [-c COLOR] [-r] FILE.mov" 2>&1
    exit 1
fi
BASEDIR=$(dirname "${BASH_SOURCE[0]}")

while getopts "d:c:r" arg; do
    case ${arg} in
      c) export COLOR="${OPTARG}" ;;
      d) export DURATION="${OPTARG}" ;;
      r) RAW=1 ;;
    esac
done
shift "$((OPTIND-1))"
FILE=$1
TESTSRC=$(${BASEDIR}/testsrc)
if [[ ${RAW} -eq 1 ]]; then
    ffmpeg -f lavfi -i ${TESTSRC} -f rawvideo -video_size 640x360 -pixel_format rgb24 -framerate 30 -y ${FILE}
else
    ffmpeg -f lavfi -i ${TESTSRC} -f mov -vcodec rawvideo -pix_fmt uyvy422 -framerate 30 -vtag yuvs -y ${FILE}
fi
