#!/usr/bin/env bash

FIXTURE_DIR=${1:?Usage: $(basename $0) FIXTURE_DIR OUTPUT_DIR}
OUTPUT_DIR=${2:?Usage: $(basename $0) FIXTURE_DIR OUTPUT_DIR}

BASEDIR=$(dirname "${BASH_SOURCE[0]}")

FAILED=()
COMPARE_RE='.* (\(.*\))'
MAXDIFF=0.003
for PLUGIN in frei0r mlt; do
    mkdir -p "$OUTPUT_DIR/$PLUGIN/compare"

    env SHELLOPTS=xtrace PLUGIN=$PLUGIN "${BASEDIR}/extract_frames" "$OUTPUT_DIR/$PLUGIN"

    for fixture in "${FIXTURE_DIR}/${PLUGIN}/"*.png; do
        name=$(basename "$fixture")
        # ImageMagick compare
        compare=$(compare -metric Fuzz "$fixture" "${OUTPUT_DIR}/${PLUGIN}/${name}" "${OUTPUT_DIR}/${PLUGIN}/compare/${name}" 2>&1)
        if [ 2 -eq $? ] || [[ "$compare" =~ $COMPARE_RE ]] && [ 1 -eq "$(echo "${BASH_REMATCH[1]} > $MAXDIFF" | bc)" ]; then
            FAILED+=("${PLUGIN}/${name}=${BASH_REMATCH[1]}")
        fi
    done
done

if [ ${#FAILED[*]} != 0 ]; then
    echo Failed: ${FAILED[@]}
    exit 1
fi
