#!/usr/bin/env bash

FIXTURE_DIR=${1:?Usage: $(basename $0) FIXTURE_DIR OUTPUT_DIR}
OUTPUT_DIR=${2:?Usage: $(basename $0) FIXTURE_DIR OUTPUT_DIR}

BASEDIR=$(dirname "${BASH_SOURCE[0]}")

mkdir -p "${OUTPUT_DIR}/compare"
"${BASEDIR}/gen_frames" "$OUTPUT_DIR"

FAILED=()
for fixture in "${FIXTURE_DIR}/"*.png; do
    name=$(basename "$fixture")
    # ImageMagick compare
    if ! compare -metric MAE "$fixture" "${OUTPUT_DIR}/${name}" "${OUTPUT_DIR}/compare/${name}"; then
        FAILED+=(name)
    fi
done
if [ ${#FAILED[*]} != 0 ]; then
    echo Failed: ${FAILED[@]}
    exit 1
fi
