#!/bin/bash

BASEDIR=$(dirname "${BASH_SOURCE[0]}")
export DISPLAY=${DISPLAY:-:0}
case ${PLUGIN:-frei0r} in
frei0r)
    PRODUCER=("frei0r.webvfx_source" "0=\"webvfx --duration 199/30 --width {{width}} --height {{height}} ${BASEDIR}/../examples/producer-demo.qml\"")
    ;;
mlt)
    PRODUCER=(mltwebvfx:"webvfx --width {{width}} --height {{height}} ${BASEDIR}/../examples/producer-demo.qml")
    ;;
esac
melt -verbose \
    -producer "${PRODUCER[@]}" length=199 \
    $(eval echo $(< "${VFX_CONSUMER:-${BASEDIR}/consumer_sdl}")) mlt_profile=${BASEDIR}/webvfx_profile
