#!/bin/bash

BASEDIR=$(dirname "${BASH_SOURCE[0]}")
export DISPLAY=${DISPLAY:-:0}
case ${PLUGIN:-frei0r} in
frei0r)
    FILTER=("frei0r.webvfx_filter" "0=\"\"${BASEDIR}/../examples/filter-banner.qml?webvfx_duration=300/30&Title=WebVfx Banner Demo&FadeIn=20&FadeOut=20\"\"")
    ;;
mlt)
    FILTER=(mltwebvfx:"${BASEDIR}/../examples/filter-banner.qml?Title=WebVfx Banner Demo&FadeIn=20&FadeOut=20")
    ;;
esac
REDTESTSRC=lavfi:$(COLOR=red ${BASEDIR}/tests/testsrc)
melt -verbose "${VFX_SOURCE:-${REDTESTSRC}}" out=299 \
    -filter "${FILTER[@]}" out=299 \
    $(eval echo $(< "${VFX_CONSUMER:-${BASEDIR}/consumer_sdl}")) mlt_profile=${BASEDIR}/webvfx_profile
