#!/bin/bash

DISPLAY=${DISPLAY:-:0} WEBVFX_DATA=${WEBVFX_DATA:-../examples} melt "${VFX_SOURCE:-red.mlt}" out=499 -track -blank 199 "${VFX_TARGET:-blue.mlt}" out=499 -transition webvfx.transition.demo.html in=200 out=499 producer.backgroundImage.resource="${VFX_BACKGROUND:-green.mlt}" title="${VFX_TITLE:-Testing WebVfx Transition}" $(eval echo $(< "${VFX_CONSUMER:-consumer_sdl}"))
