#!/bin/bash

export DISPLAY=${DISPLAY:-:0}
"${VFX_MELT:-melt}" -verbose "${VFX_SOURCE:-red.mlt}" out=149 \
    -track -blank 59 \
    "${VFX_TARGET:-blue.mlt}" out=149 \
    -transition webvfx:../examples/transition-demo.html in=60 out=149 \
        producer.backgroundImage.resource="${VFX_BACKGROUND:-green.mlt}" \
        title="${VFX_TITLE:-Testing WebVfx Transition}" \
    $(eval echo $(< "${VFX_CONSUMER:-consumer_sdl}"))
