#!/bin/bash

DISPLAY=${DISPLAY:-:0} WEBVFX_DATA=${WEBVFX_DATA:-../examples} melt -producer webvfx.producer.demo.html out=499 title="${VFX_TITLE:-WebVfx Producer Demo}" $(eval echo $(< "${VFX_CONSUMER:-consumer_sdl}"))
