#!/bin/bash

BASEDIR=$(dirname "${BASH_SOURCE[0]}")
export DISPLAY=${DISPLAY:-:0}
melt -verbose "${VFX_SOURCE:-red.mlt}" out=299 \
    -filter webvfx:${BASEDIR}/../examples/filter-banner.qml out=299 \
        Title="${VFX_TITLE:-WebVfx Banner Demo}" \
        FadeIn="${VFX_FADEIN:-20}" \
        FadeOut="${VFX_FADEOUT:-20}" \
    $(eval echo $(< "${VFX_CONSUMER:-consumer_sdl}")) mlt_profile=${BASEDIR}/webvfx_profile
