#!/bin/bash

export DISPLAY=${DISPLAY:-:0}
"${VFX_MELT:-melt}" -verbose \
    -producer webvfx:../examples/producer-demo.html length=199 \
        title="${VFX_TITLE:-WebVfx Producer Demo}" \
    $(eval echo $(< "${VFX_CONSUMER:-consumer_sdl}"))
