#!/bin/bash

BASEDIR=$(dirname "${BASH_SOURCE[0]}")
export DISPLAY=${DISPLAY:-:0}
melt -verbose \
    "${VFX_SOURCE:-${BASEDIR}/red.mlt}" out=349 \
    "${VFX_TARGET:-${BASEDIR}/blue.mlt}" out=349 \
    -mix 120 -mixer webvfx:${BASEDIR}/../examples/transition-simple.qml \
    "${VFX_EXTRA:-${BASEDIR}/green.mlt}" out=349 \
    -mix 120 -mixer webvfx:${BASEDIR}/../examples/transition-simple.qml \
    $(eval echo $(< "${VFX_CONSUMER:-${BASEDIR}/consumer_sdl}")) mlt_profile=${BASEDIR}/webvfx_profile
