#!/bin/bash

BASEDIR=$(dirname "${BASH_SOURCE[0]}")
export DISPLAY=${DISPLAY:-:0}
case ${PLUGIN:-frei0r} in
frei0r)
    FILTER=("frei0r.webvfx_filter" "0=\"\"webvfx --duration 300/30 --width {{width}} --height {{height}} --property Title='${VFX_TITLE:-WebVfx Banner Demo}' --property FadeIn=${VFX_FADEIN:-20} --property FadeOut=${VFX_FADEOUT:-20} ${BASEDIR}/../examples/filter-banner.qml\"\"")
    ;;
mlt)
    FILTER=(mltwebvfx:"webvfx --width {{width}} --height {{height}} --property Title='${VFX_TITLE:-WebVfx Banner Demo}' --property FadeIn=${VFX_FADEIN:-20} --property FadeOut=${VFX_FADEOUT:-20} ${BASEDIR}/../examples/filter-banner.qml")
    ;;
esac
REDTESTSRC=lavfi:$(COLOR=red ${BASEDIR}/tests/testsrc)
melt -verbose "${VFX_SOURCE:-${REDTESTSRC}}" out=299 \
    -filter "${FILTER[@]}" out=299 \
    $(eval echo $(< "${VFX_CONSUMER:-${BASEDIR}/consumer_sdl}")) mlt_profile=${BASEDIR}/webvfx_profile
