#!/bin/bash

export DISPLAY=${DISPLAY:-:0}
"${VFX_MELT:-melt}" -verbose "${VFX_SOURCE:-red.mlt}" out=299 \
    -filter webvfx:../examples/filter-demo.html out=299 \
    $(eval echo $(< "${VFX_CONSUMER:-consumer_sdl}"))
