#!/bin/bash

BASEDIR=$(dirname "${BASH_SOURCE[0]}")
$BASEDIR/create_mov
export DISPLAY=${DISPLAY:-:0}
melt -verbose \
    "${VFX_SOURCE:-${BASEDIR}/red.mov}" out=349 \
    "${VFX_TARGET:-${BASEDIR}/blue.mov}" out=349 \
    -mix 120 -mixer vfxpipe:"webvfx_frameserver --width ${VFXPIPE_WIDTH} --height ${VFXPIPE_HEIGHT} --image SourceImage --image TargetImage ${BASEDIR}/../examples/transition-simple.qml" \
    "${VFX_EXTRA:-${BASEDIR}/green.mov}" out=349 \
    -mix 120 -mixer vfxpipe:"webvfx_frameserver --width ${VFXPIPE_WIDTH} --height ${VFXPIPE_HEIGHT} --image SourceImage --image TargetImage ${BASEDIR}/../examples/transition-simple.qml" \
    $(eval echo $(< "${VFX_CONSUMER:-${BASEDIR}/consumer_sdl}")) mlt_profile=${BASEDIR}/webvfx_profile
