#!/bin/bash

BASEDIR=$(dirname "${BASH_SOURCE[0]}")
export DISPLAY=${DISPLAY:-:0}
case ${PLUGIN:-frei0r} in
frei0r)
    TRANSITION=("frei0r.webvfx_mixer2" "0=\"\"webvfx --duration 120/30 --width {{width}} --height {{height}} '${BASEDIR}/../examples/transition-demo3d.qml?title=Hello 3D!'\"\"")
    ;;
mlt)
    TRANSITION=(mltwebvfx:"webvfx --width {{width}} --height {{height}} '${BASEDIR}/../examples/transition-demo3d.qml?title=Hello 3D!'")
    ;;
esac
REDTESTSRC=lavfi:$(COLOR=red ${BASEDIR}/tests/testsrc)
BLUETESTSRC=lavfi:$(COLOR=blue ${BASEDIR}/tests/testsrc)
melt -verbose \
    "${VFX_SOURCE:-${REDTESTSRC}}" out=349 \
    "${VFX_TARGET:-${BLUETESTSRC}}" out=349 \
    -mix 120 -mixer "${TRANSITION[@]}" \
    $(eval echo $(< "${VFX_CONSUMER:-${BASEDIR}/consumer_sdl}")) mlt_profile=${BASEDIR}/webvfx_profile
