#!/bin/bash

BASEDIR=$(dirname "${BASH_SOURCE[0]}")
export DISPLAY=${DISPLAY:-:0}
FRAG=${BASEDIR}/../examples/crossZoom.frag
QSB=${BASEDIR}/../../build/crossZoom.qsb
if [ "${FRAG}" -nt "${QSB}" ]; then
    qsb --glsl "100 es,120,150,400" --hlsl 50 --msl 12 -o "${QSB}" "$FRAG"
fi
case ${PLUGIN:-frei0r} in
frei0r)
    TRANSITION=("frei0r.webvfx_mixer2" "0=\"\"${BASEDIR}/../examples/transition-shader-crosszoom.qml?webvfx_duration=120/30&Strength=0.3\"\"")
    ;;
mlt)
    TRANSITION=(mltwebvfx:"${BASEDIR}/../examples/transition-shader-crosszoom.qml?Strenth=0.3")
    ;;
esac
REDTESTSRC=lavfi:$(COLOR=red ${BASEDIR}/tests/testsrc)
BLUETESTSRC=lavfi:$(COLOR=blue ${BASEDIR}/tests/testsrc)
GREENTESTSRC=lavfi:$(COLOR=green ${BASEDIR}/tests/testsrc)
# Extra producer not supported by frei0r
#producer.0.resource="${VFX_TARGET:-${GREENTESTSRC}}"
melt -verbose \
    "${VFX_SOURCE:-${REDTESTSRC}}" out=349 \
    "${VFX_TARGET:-${BLUETESTSRC}}" out=349 \
    -mix 120 -mixer "${TRANSITION[@]}" \
    $(eval echo $(< "${VFX_CONSUMER:-${BASEDIR}/consumer_sdl}")) mlt_profile=${BASEDIR}/webvfx_profile
