#!/bin/bash

export DISPLAY=${DISPLAY:-:0}
export WEBVFX_DATA=${WEBVFX_DATA:-$PWD/../examples}
melt "${VFX_SOURCE:-red.mlt}" out=399 \
    -track -blank 99 \
    "${VFX_TARGET:-blue.mlt}" out=399 \
    -transition webvfx.transition.demo3d.qml in=100 out=399 \
        title="${VFX_TITLE:-Hello 3D!}" \
    $(eval echo $(< "${VFX_CONSUMER:-consumer_sdl}"))
