#!/bin/bash

export DISPLAY=${DISPLAY:-:0}
export WEBVFX_DATA=${WEBVFX_DATA:-$PWD/../examples}
"${VFX_MELT:-melt}" "${VFX_SOURCE:-red.mlt}" out=299 \
    -filter webvfx.filter.demo.html out=299 \
    $(eval echo $(< "${VFX_CONSUMER:-consumer_sdl}"))
