name: CI
on:
  push:
    branches:
      - '*'

jobs:

  linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup buildx
      uses: docker/setup-buildx-action@v2
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    - name: Buildx
      uses: docker/build-push-action@v3
      with:
        push: false
        context: builders/linux
        tags: webvfx
        load: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new
    # https://github.com/docker/build-push-action/issues/252
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
    - name: Test
      run: builders/linux/docker-run.sh
    - name: Upload Failed Artifacts
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: failed-images-linux
        path: build/linux/output

  macos:
    runs-on: macos-12
    env:
      XCODE_VER: 14.2
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Xcode
      run: |
        sudo xcode-select -s "/Applications/Xcode_${XCODE_VER}.app"
    - name: Restore cached installation
      uses: actions/cache/restore@v3
      id: restore-cache
      with:
        path: build/macos/installed
        key: ${{ runner.os }}-${{ hashFiles('builders/macos/versions') }}-${{ env.XCODE_VER }}
    - name: Build installation
      if: steps.restore-cache.outputs.cache-hit != 'true'
      run: |
        builders/macos/macos-build.sh
    - name: Save cached installation
      uses: actions/cache/save@v3
      if: steps.restore-cache.outputs.cache-hit != 'true'
      with:
        path: build/macos/installed
        key: ${{ steps.restore-cache.outputs.cache-primary-key }}
    - name: Install WebVfx
      run: |
        builders/macos/webvfx-build.sh
    - name: Test
      # Disable for now, no GPU on macos
      # https://github.com/actions/virtual-environments/issues/1779#issuecomment-707071183
      if: false
      run: |
        builders/macos/webvfx-runtests.sh
    - name: Failed Artifacts
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: failed-images-macos
        path: build/macos/output
