name: CI
on:
  push:
    branches:
      - '*'

jobs:

  linux:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    # - name: Test
    #   run: |
    #     docker/docker-run.sh "${{ github.workspace }}"
    - name: Upload Failed Artifacts
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: failed-images-linux
        path: demo/mlt/tests/fixtures/output

  macos:
    runs-on: macos-10.15
    env:
      QT_VER: 6.0.0
      MLT_VER: 6.24.0
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Provision
      run: |
        sudo xcode-select -s "/Applications/Xcode_11.7.app"
        brew install imagemagick pkg-config ffmpeg
    - name: Cache Qt6
      uses: actions/cache@v2
      id: qt6-cache
      with:
        path: qt-everywhere-src-${QT_VER}
        key: ${{ runner.os }}-qt6-${{ env.QT_VER }}
    - name: Build Qt6
      if: steps.qt6-cache.outputs.cache-hit != 'true'
      run: |
        brew install cmake ninja
        curl -L http://download.qt.io/official_releases/qt/6.0/${QT_VER}/single/qt-everywhere-src-${QT_VER}.tar.xz | tar xJf -
        cd qt-everywhere-src-${QT_VER}
        ./configure
        cmake --build . --parallel
    - name: Install Qt6
      run: |
        cd qt-everywhere-src-${QT_VER}
        sudo cmake --install .
    - name: Cache MLT
      uses: actions/cache@v2
      id: mlt-cache
      with:
        path: mlt-${MLT_VER}
        key: ${{ runner.os }}-mlt-${{ env.MLT_VER }}-v2
    - name: Build MLT
      if: steps.mlt-cache.outputs.cache-hit != 'true'
      run: |
        curl -L https://github.com/mltframework/mlt/releases/download/v${MLT_VER}/mlt-${MLT_VER}.tar.gz | tar xzf -
        cd mlt-${MLT_VER}
        ./configure
        make
    - name: Install MLT
      run: |
        cd mlt-${MLT_VER}
        sudo make install
    # - name: Install WebVfx
    #   run: |
    #     mkdir build
    #     cd build
    #     qmake ..
    #     sudo make install
    # - name: Test
    #   # Disable for now, no GPU on macos
    #   # https://github.com/actions/virtual-environments/issues/1779#issuecomment-707071183
    #   if: false
    #   run: |
    #     cd demo/mlt/tests
    #     mkdir -p fixtures/output
    #     ./runtests fixtures/macos fixtures/output
    - name: Failed Artifacts
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: failed-images-macos
        path: demo/mlt/tests/fixtures/output
