name: macos
on:
  push:
    branches:
      - '*'
jobs:
  macos:
    runs-on: macos-10.15
    env:
      QT_VER: 6.0.0
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Provision
      run: |
        sudo xcode-select -s "/Applications/Xcode_11.7.app"
        brew install imagemagick pkg-config mlt
    - name: Cache Qt6
      uses: actions/cache@v2
      id: qt6-cache
      with:
        path: qt6-build
        key: ${{ runner.os }}-qt-${{ env.QT_VER }}
    - name: Build Qt6
      if: steps.qt6-cache.outputs.cache-hit != 'true'
      run: |
        brew install cmake ninja
        curl -L http://download.qt.io/official_releases/qt/6.0/${QT_VER}/single/qt-everywhere-src-${QT_VER}.tar.xz | tar xJf -
        mkdir qt6-build
        cd qt6-build
        ../qt-everywhere-src-${QT_VER}/configure && cmake --build . --parallel
    - name: Install Qt6
      run: |
        cd qt6-build && sudo cmake --install .
    - name: Install WebVfx
      run: |
        mkdir build
        cd build
        qmake ..
        sudo make install
    - name: Test
      run: |
        cd demo/mlt/tests
        mkdir -p fixtures/output
        ./runtests fixtures/macos fixtures/output
    - name: Failed Artifacts
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: failed-images
        path: demo/mlt/tests/fixtures/output
